### PR TITLE
Remove redundant reflect metadata import

### PR DESCRIPTION
**Pull request by mzalevski**
`import reflect-metadata` is not needed in this example. I left it by mistake.

It is needed when you use `class-transformer`, e.g.
```tsx
import "reflect-metadata"; // Here! But it's preffered to import it only once in place like `src/index.tsx`
import { Length, ValidateNested } from "class-validator";
import { Type } from "class-transformer"; // So we must import reflect-metadata, like above ^

class Friend {
  @Length(3, 30)
  username: string;
}

export class User {
  @Length(3, 30)
  username: string;

  @ValidateNested()
  @Type(() => Friend)
  bestFriend: Friend;
}
```

### CODE REVIEW

**Comment by mzalevski** [comment]
btw @jorisre we should add `class-validator` here:
image

**Review by bluebill1049 — APPROVED** [review]

**Comment by bluebill1049** [comment]
Done 👍

**Comment by mzalevski** [comment]
Thanks @bluebill1049 ! Is it possible to change the code snippet in [the tweet about new resolver](https://twitter.com/HookForm/status/1381509773401628672)? Or should I comment there about this redundant import?

**Comment by bluebill1049** [comment]
> Thanks @bluebill1049 ! Is it possible to change the code snippet in [the tweet about new resolver](https://twitter.com/HookForm/status/1381509773401628672)? Or should I comment there about this redundant import?

It's a bit too late. I think it's fine, if users interested they will refer to the repo here.

**Comment by bluebill1049** [comment]
> Thanks @bluebill1049 ! Is it possible to change the code snippet in [the tweet about new resolver](https://twitter.com/HookForm/status/1381509773401628672)? Or should I comment there about this redundant import?

you can comment under the tweet tho.

**Comment by mzalevski** [comment]
@bluebill1049 commented. btw could you add "Class Validator" here too ^^
image

**Pull request merged**
