### PR TITLE
V2 🚀

### PR DESCRIPTION
**Pull request by jorisre**
# Resolvers V2 🚀 

Root branch for V2 work.

## Update to react-hook-form v7 - #118 

**Breaking changes**: **yes**  🟥

- Require react-hook-form >= 7

## Global improvements

**Breaking changes**: **no**  🟩 

- Add code of conduct
- Add contributing
- Add issue template
- Add funding
- Release process: add beta branch
- Vest: fix validate all criteria #110
- Better TypeScript support #110
- Add tests #110

***

## Improve bundle output format: CJS, ESM & UMD - https://github.com/react-hook-form/resolvers/pull/104

First of all, huge thank to the [preact](https://github.com/preactjs/preact) hard work. This PR is heavily inspired of their modules structure.

**Breaking changes**: **no**  🟩 

**Related**: https://github.com/react-hook-form/resolvers/issues/71 & https://github.com/react-hook-form/resolvers/issues/100

- Remove IE11 support
- Move resolvers into separate folders
- Use [microbundle](https://github.com/developit/microbundle) to generate bundles
- Multiple bundles per resolver: CJS, ESM, UMD _(modern coming later)_
- Add exports map in package.json + support node 13 _(thank to preact)_

***

## Support sync/async validation

**Breaking changes**: **no**  🟩 

Related to #88 
Resolver get a third optional param. Async mode is set by default.

Before:
```ts
useForm({
    resolver: zodResolver(schema, schemaOptions)
})
```

After:
```ts
useForm({
    resolver: zodResolver(schema, schemaOptions, { mode: 'async' | 'sync' })
})
```

- [x] Zod #114 
- [x] Yup #115 
- [x] Joi #116 
- [x] Vest #117 
- [x] Superstruct - **No async support**

***

## Pass down Joi context - #124 

**Breaking changes**: **no**  🟩 

Related to https://github.com/react-hook-form/resolvers/issues/121

***

## Zod resolver: add union errors + reduce bundle size by ~23% - #126 

**Breaking changes**: **no**  🟩 

Related to #119 

***

## Add error's reference - #127 

**Breaking changes**: **no**  🟩 

Related to #77 

***

## Reduce resolvers's size

**Breaking changes**: **no**  🟩 

- [zod resolver](https://github.com/react-hook-form/resolvers/pull/126) ~23%
- [vest resolver](https://github.com/react-hook-form/resolvers/pull/129) ~46%
- [superstruct resolver](https://github.com/react-hook-form/resolvers/pull/128) ~75%
- [joi resolver](https://github.com/react-hook-form/resolvers/pull/131) ~25%
- [yup resolver](https://github.com/react-hook-form/resolvers/pull/130) ~28%

### CODE REVIEW

**Comment by bluebill1049** [comment]
Can we remove `transformToNestObject` import from react-hook-form?

```
// Todo: to be removed
import set from '../utils/set';
import isKey from '../utils/isKey';
import { FieldValues } from '../types';

export default (data: FieldValues, value: Record<string, any> = {}): any => {
  for (const key in data) {
    !isKey(key) ? set(value, key, data[key]) : (value[key] = data[key]);
  }
  return value;
};
```

I think we can export `set` function from `react-hook-form`.

**Comment by jorisre** [comment]
> Can we remove `transformToNestObject` import from react-hook-form?
> 
> ```tsx
> // Todo: to be removed
> import set from '../utils/set';
> import isKey from '../utils/isKey';
> import { FieldValues } from '../types';
> 
> export default (data: FieldValues, value: Record<string, any> = {}): any => {
>   for (const key in data) {
>     !isKey(key) ? set(value, key, data[key]) : (value[key] = data[key]);
>   }
>   return value;
> };
> ```
> 
> I think we can export `set` function from `react-hook-form`.
> 
> I did a quick test by removed that function `transformToNestObject`, looks like only `vest` needs it.
> Screen Shot 2021-01-19 at 7 27 07 pm

Yes you can replace this function

**Comment by bluebill1049** [comment]
I will release a patch on react hook form 6.14.3 to export `set` and send you a PR.

**Comment by bluebill1049** [comment]
Screen Shot 2021-02-08 at 2 25 57 pm

Hey @jorisre, 

More of a question, Do we need to include the src folders? cause i didn't include `src` in `react-hook-form`.

**Comment by jorisre** [comment]
Hey @bluebill1049 
I'm not sure to understand, what's your needs ?

**Comment by bluebill1049** [comment]
It's minor don't worry about it @jorisre. I was referring to the `src` folder been generated inside of `dist` during the build.

**Comment by bummey** [comment]
I noticed that the `superstruct` types are missing from the root of the package. Is that normal? (2.0.0-rc.1)
Screenshot 2021-02-23 at 12 35 55

**Review by bluebill1049 — APPROVED** [review]

**Pull request merged**
