### PR TITLE
Fix modules resolution

### PR DESCRIPTION
**Pull request by jorisre**
Heya 👋🏻 

This should fix https://github.com/react-hook-form/resolvers/issues/20

Resolver could be imported like this:

```ts
import { yupResolver } from '@hookform/resolvers/yup'; 
import { joiResolver } from '@hookform/resolvers/joi'; 
import { superstructResolver } from '@hookform/resolvers/superstruct'; 
```

<details>
    <summary>Old purpose</summary>

Now, it generates theses folders : 
```
dist/
    types/
    ie11/
    cjs/
    umd/
    esm/
```

Typings are generated separately _(maybe we could do better)_.
I've done a little rework on rollup config.
I've tested all bundles _(esm, umd, cjs (ie11))_.  I've kept the write cjs step at build time to generate prod|dev bundles.
And finally No Breaking Changes : `import { yupResolver } from '@hookform/resolvers`

</details>

I hope I could test a beta soon :)
Any improvements are welcome :) Let me know what you think !

### CODE REVIEW

**Comment by bluebill1049** [comment]
oh wow! THANK YOU! you are my hero... i was almost going to do mono repo and disturb multiple packages. (which is shit and annoying)

**Comment by bluebill1049** [comment]
here is the beta: `@hookform/resolvers@0.2.0-beta.9`

**Comment by jorisre** [comment]
👋🏻 
Thanks @bluebill1049 :)

Below, some working examples with `@hookform/resolvers@0.2.0-beta.9`

**UMD with Joi validation:**
➡️  &nbsp; https://codesandbox.io/s/example-hookformresolvers-beta-umd-gworo

**ESM module with Joi validation:**
➡️  &nbsp; https://codesandbox.io/s/example-hookformresolvers-beta-esm-xxu0d

**CJS(IE11) module with Yup validation:**
➡️  &nbsp; https://codesandbox.io/s/example-hookformresolvers-beta-cjsie11-dms1i
Deployed here: https://csb-dms1i.joris.vercel.app

I'm getting a bug with superstruct _(again  :/)_ when settings `skipLibCheck: false`. It look like generated types are wrongs.

<details>
    <summary>At build time & inside generated types</summary>

Capture d’écran 2020-09-19 à 19 41 57
Capture d’écran 2020-09-19 à 19 43 02
</details>

I'm on it :)

**Comment by bluebill1049** [comment]
hey, @jorisre I have tested with the following repo:

https://github.com/avin-kavish/cra-ts-hook-form-resolver-issue

looks like the issue still persist: with the latest `@hookform/resolvers@0.2.0-beta.10`

Screen Shot 2020-09-20 at 10 51 48 am

**Comment by jorisre** [comment]
> hey, @jorisre I have tested with the following repo:
> 
> https://github.com/avin-kavish/cra-ts-hook-form-resolver-issue
> 
> looks like the issue still persist: with the latest `@hookform/resolvers@0.2.0-beta.10`
> 
> Screen Shot 2020-09-20 at 10 51 48 am

Okay, I'll try another thing 🤞🏻

**Comment by bluebill1049** [comment]
Thanks @jorisre

**Comment by bluebill1049** [comment]
`0.2.0-beta.11 ` 👍

**Comment by bluebill1049** [comment]
Thanks, @jorisre this works!! I think we will be looking for a major update then, do you know any solution so i don't have to publish inside the dist folder (not biggie tho, i can live with that)

**Review by bluebill1049 — APPROVED** [review]

**Comment by jorisre** [comment]
@bluebill1049 I will push some changes again :)
I hope this will be the last push

**Comment by bluebill1049** [comment]
No worries, mate. really awesome stuff! this should unlock the Zod resolver as well. we can push a really nice major version with a new resolver. 💥

**Comment by jorisre** [comment]
@bluebill1049 should be good now

> do you know any solution so i don't have to publish inside the dist folder (not biggie tho, i can live with that)

We can do something like next.js does: https://github.com/vercel/next.js/blob/canary/packages/next/head.js

**Comment by bluebill1049** [comment]
> @bluebill1049 should be good now
> 
> > do you know any solution so i don't have to publish inside the dist folder (not biggie tho, i can live with that)
> 
> We can do something like next.js does: https://github.com/vercel/next.js/blob/canary/packages/next/head.js

oh, that's smart! shall we do that? 💯

**Comment by jorisre** [comment]
> > @bluebill1049 should be good now
> > > do you know any solution so i don't have to publish inside the dist folder (not biggie tho, i can live with that)
> > 
> > 
> > We can do something like next.js does: https://github.com/vercel/next.js/blob/canary/packages/next/head.js
> 
> oh, that's smart! shall we do that? 💯

If we do this, keep in mind, we should create two files for each resolvers at the project root:
```
yup.js // require('./dist/yup.js');
yup.d.ts // export * from './dist/yup.d.ts';
joi.js // require('./dist/joi.js');
joi.d.ts // export * from './dist/joi.d.ts';
superstruct.js // require('./dist/superstruct.js');
superstruct.d.ts // export * from './dist/superstruct.d.ts';
```

if you're ok, I can do it

**Comment by bluebill1049** [comment]
> > > @bluebill1049 should be good now
> > > > do you know any solution so i don't have to publish inside the dist folder (not biggie tho, i can live with that)
> > > 
> > > 
> > > We can do something like next.js does: https://github.com/vercel/next.js/blob/canary/packages/next/head.js
> > 
> > 
> > oh, that's smart! shall we do that? 💯
> 
> If we do this, keep in mind, we should create two files for each resolvers at the project root:
> 
> ```
> yup.js // require('./dist/yup.js');
> yup.d.ts // export * from './dist/yup.d.ts';
> joi.js // require('./dist/joi.js');
> joi.d.ts // export * from './dist/joi.d.ts';
> superstruct.js // require('./dist/superstruct.js');
> superstruct.d.ts // export * from './dist/superstruct.d.ts';
> ```
> 
> if you're ok, I can do it

Yea, thanks @jorisre let's do that please, sorry to keep trouble you 🙏

**Comment by jorisre** [comment]
@bluebill1049 Done ✅  Let me know if need some changes

**Comment by bluebill1049** [comment]
I will release a @next version on this! if everything goes well, we will introduce this major update.

**Comment by jorisre** [comment]
[All examples](https://github.com/react-hook-form/resolvers/pull/60#issuecomment-695337354) have been updated with the last releasehttps://github.com/react-hook-form/resolvers/releases/tag/v1.0.0-rc.1

**Pull request merged**
