### PR TITLE
Add Typanion Resolver

### PR DESCRIPTION
**Pull request by stramel**
I believe I covered everything except adding it to the Bug Report template which seems to be lacking a few other resolvers currently as well.

Fixes https://github.com/react-hook-form/react-hook-form/discussions/6099

### CODE REVIEW

**Review by bluebill1049 — APPROVED** [review]
LGTM 🥳

**Comment by stramel** [comment]
Feel free to merge whenever you guys are happy with it 👍🏼

**Comment by bluebill1049** [comment]
@jorisre i will merge it next week if you are busy. 🙏

**Review by jorisre — APPROVED** [review]
LGTM!

Thank you @stramel :)

**Comment by stramel** [comment]
@jorisre did this break something?

**Comment by jorisre** [comment]
Nope. I just forgot to rewrite the commit message to match with semantic release. @bluebill1049 will trigger the release manually :)

**Pull request merged**
