### PR TITLE
Upgrade and migrate Valibot to v0.31.0

### PR DESCRIPTION
**Pull request by fabian-hiller**
https://valibot.dev/guides/migrate-to-v0.31.0/

### CODE REVIEW

**Comment by fabian-hiller** [comment]
Please don't merge. I want to improve something first.

**Comment by fabian-hiller** [comment]
Done. The PR should be ready now. 🫡

**Comment by bluebill1049** [comment]
thank you very much @fabian-hiller sorry, could you please resolve the conflict?

**Review by bluebill1049 — DISMISSED** [review]

**Comment by fabian-hiller** [comment]
This is a conflict in the `pnpm-lock.yaml` file. Should I just overwrite it, or do you want to take care of it?

**Comment by bluebill1049** [comment]
Could you overwrite it, please?

**Comment by fabian-hiller** [comment]
Done

**Review by bluebill1049 — APPROVED** [review]

**Comment by fabian-hiller** [comment]
v0.31.0 is available: https://valibot.dev/blog/valibot-v0.31.0-is-finally-available/

**Pull request merged**
