### PR TITLE
esm support to fix bundler incompatibility

### PR DESCRIPTION
**Pull request by benallfree**
This package `dist` is currently not compatible with bundlers.

`tsc` outputs a commonjs format, but that is for node environments, not browser. It causes `Object.defineProperty(exports, "__esModule", { value: true });` to be emitted, which causes an error in a browser.

I updated `tsconfig.json` to output `esnext` instead, and that fixes the problem.

See for more info: https://blog.rendall.dev/posts/2019/1/14/problem-typescript-adds-objectdefinepropertyexports-esmodule-value-true/

### CODE REVIEW

**Comment by jorisre** [comment]
👋🏻  @benallfree 
Thanks for your work!
Do you also have this [problem](https://github.com/react-hook-form/resolvers/issues/71) ?

**Comment by benallfree** [comment]
@jorisre Yes, this fixes #71. Thanks for catching that!

**Review by jorisre — APPROVED** [review]
LGTM Thanks @benallfree !

**Comment by bluebill1049** [comment]
Thanks @jorisre shall we do a release with it today?

**Comment by jorisre** [comment]
> Thanks @jorisre shall we do a release with it today?

Yes you can :)

**Comment by bluebill1049** [comment]
@jorisre sent you a private message at twitter.

**Comment by benallfree** [comment]
Any thought on when the updated npm package will be published? I have to maintain my own branch with a `build` folder until the package is published

**Pull request merged**
