### PR TITLE
feat(context): inject context into yup context

### PR DESCRIPTION
**Pull request by Vandell63**
Hey there,
-> https://github.com/react-hook-form/resolvers/issues/29
Test + context injected
I prefer to don't dive test because i will make another mr for -> https://github.com/react-hook-form/resolvers/issues/26#issuecomment-659114319.
And then push test to 100%

### CODE REVIEW

**Comment by Vandell63** [comment]
Schema should be test inside `describe` because if it was outside, the spy still in other test.
I go to -> https://github.com/react-hook-form/resolvers/issues/26#issuecomment-659218254.
And then i really like to fixed that if you can help me as much as you can -> https://github.com/react-hook-form/react-hook-form/issues/2222

**Comment by bluebill1049** [comment]
@Vandell63 you happy for this PR to be merged?

**Comment by Vandell63** [comment]
> @Vandell63 you happy for this PR to be merged?

Of course yes :) if it is all fine for you :+1:

**Comment by tommedema** [comment]
Tried to migrate to react-hook-form 6.0.7 with "@hookform/resolvers": "^0.0.6", but my yup schema is not actually used and validation passes with invalid values:

```
  const {
    register,
    handleSubmit,
    watch,
    errors,
    formState,
    reset,
    setValue,
  } = useForm<IFormValues>({
    context: {
      renderFields,
      isParticipantsRequired,
    },
    resolver: yupResolver(formSchema, {
      context: {
        renderFields,
        isParticipantsRequired,
      }
    })
  })
```

**Comment by bluebill1049** [comment]
@tommedema provide a codesandbox

**Comment by Vandell63** [comment]
@tommedema please can you retry with this shape instead and give me your feedback ?
```
  const {
    register,
    handleSubmit,
    watch,
    errors,
    formState,
    reset,
    setValue,
  } = useForm<IFormValues>({
    context: {
      renderFields,
      isParticipantsRequired,
    },
    resolver: yupResolver(formSchema)
  })
```
Or if you want your context to be used inside of the yup options with abortEarly set to false
```
  const {
    register,
    handleSubmit,
    watch,
    errors,
    formState,
    reset,
    setValue,
  } = useForm<IFormValues>({
    resolver: yupResolver(formSchema, {
      abortEarly: false,
      context: {
        renderFields,
        isParticipantsRequired,
      }
    })
  })
```

**Pull request merged**
