### PR TITLE
fix #275

### LINKED ISSUE #275: DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at node_modules\@hookform\resolvers\package.json
I've upgraded NextJS version to v12 and changed importing path of yupResolver.

```js
import { yupResolver } from "@hookform/resolvers/yup/dist/yup";
```

That seems like work well in dev, but I get this when I build to production.

image

### PR DESCRIPTION
**Pull request by JamesWong1999**
fix #275 with deprecate warning

### CODE REVIEW

**Review by bluebill1049 — APPROVED** [review]

**Comment by bluebill1049** [comment]
thanks @JamesWong1999 for the PR, @jorisre any idea why this one fails?

**Comment by jorisre** [comment]
It fails because `./*` is not supported by `check-exports-map`

**Comment by bluebill1049** [comment]
thanks for the PR anyhow 👍

**Comment by jorisre** [comment]
There is a similar issue on the Preact repo: https://github.com/preactjs/preact/issues/3299

**Comment by brycefranzen** [comment]
Looks like check-exports-map has had an update.  Does this work now?  Could we merge that "closed" MR now to resolve this warning?

**Comment by bluebill1049** [comment]
thanks for the contribution.

**Pull request merged**
