### PR TITLE
Feature/jsonSchema resolver

### PR DESCRIPTION
**Pull request by TheDSCPL**
Following #50 and #58

### CODE REVIEW

**Comment by TheDSCPL** [comment]
@bluebill1049

**Comment by bluebill1049** [comment]
I have reverted the change on master, we can focus on this PR.

**Comment by TheDSCPL** [comment]
Everything is working now, I think

**Comment by bluebill1049** [comment]
oh what? that quick?

**Comment by TheDSCPL** [comment]
Can you try it? I did and it's all working

**Comment by TheDSCPL** [comment]
I'm on a roll will 2 redbulls. I have a huge deliverable in a few hours. This was my break

**Comment by bluebill1049** [comment]
oh man! thank you so much, take a it easy. i will take a look over the weekend. have a good weekend mate.

**Comment by bluebill1049** [comment]
sorry, I haven't got to it at the weekend(busy)... i will try to get to it this week mate.

**Comment by TheDSCPL** [comment]
It's ok. I've been busy too! : smile:

**Comment by TheDSCPL** [comment]
It's ok! 've been busy too :)

**Comment by QuentinDejean** [comment]
hey @bluebill1049 @TheDSCPL , is there any way we can help out things rolling with that one? You guys have done a tremendous job to get this PR up and I can see that the efforts have been stalling for the past month. I'm happy to lend a hand and get it through if needed!

**Comment by TheDSCPL** [comment]
Hey. It's been in beta for a while. I guess we're waiting for issues from beta users. What do you have in mind? The only thing I remember that could still be done is to break this into separate libs so the developers don't need to install all 3 validation libraries

**Comment by bluebill1049** [comment]
hey guys, sorry for the lack of responsibility for this PR... The main repo is now fixed with type with a different package. Thanks to @jorisre 🙏 what I am hoping for is not modify the following files:

- https://github.com/react-hook-form/resolvers/pull/59/files#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0R18
- https://github.com/react-hook-form/resolvers/pull/59/files#diff-d78d8c40e5585d63387aa1f7cd3c261e2d617035b9b2aff3bf311fd565a72b6bR2

**Comment by sepehr500** [comment]
@bluebill1049 Hi! Thanks for you work with this. I was hoping to use this feature but can not find the beta branch you are referring to. Can you point me to it?

**Comment by TheDSCPL** [comment]
I'm not sure. @bluebill1049 is the one in charge of the npm part

**Comment by bluebill1049** [comment]
here is a beta version: `@hookform/resolvers@0.2.0-beta.12`

**Comment by shrugs** [comment]
it'd be cool if this resolver allowed the caller to pass their own ajv instance / compiled validation function, rather than having the lib construct it. i realize that changes the api from a json schema resolver to an AJV one, but certain features (like custom formats, keywords, etc) would be hard to support otherwise, since the resolver constructs its own AJV instance

**Comment by dpnunez** [comment]
Hey, first of all, thanks a lot for doing this feat @TheDSCPL!! I'm trying to use the `required` option, but I am not able to implement it 😿. Could someone help me to implement it?

**Comment by karlguillotte** [comment]
Hey, first, thanks a lot for adding this feature! I am using the example provided in that PR and I keep getting "should be number" for property age. Looks like value does not get parse into a number from the input. Wondering what I am doing? Should I be in charge of parsing it?

Thanks!

**Comment by karlguillotte** [comment]
@dpnunez Same problem on my side. 

Did you find a solution?

**Comment by abeMedia** [comment]
Any update on this?

**Comment by vgjenks** [comment]
Hey all, is this going anywhere?

**Pull request closed without merging**
