### PR TITLE
add `criteriaMode: all` support to class-validator resolver

### PR DESCRIPTION
**Pull request by jorisre**
- [Fix nested errors](https://github.com/react-hook-form/resolvers/commit/bcdf56bfea15a93301876c6af3a816d08d321298)
- [support `criteriaMode: all`](https://github.com/react-hook-form/resolvers/commit/a419de2aac2ceca9a92a4db5b47c0553ccac3464)
- [perf: reduce bundle size (~93% per bundle)](https://github.com/react-hook-form/resolvers/commit/c61fd8f845c2ba0024c2819ce9ecde11e668dbc6)
- Fix warning at build time: 
   >The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten

### CODE REVIEW

**Comment by jorisre** [comment]
@mzalevski Here is the changes, that was not simple to fix nested errors 😅 
Can you review this one please ? let me know it I need change something, thx

**Review by mzalevski — APPROVED** [review]
LGTM :)

**Review by bluebill1049 — APPROVED** [review]
LGTM!

**Comment by bluebill1049** [comment]
Awesome stuff @jorisre The package size reduction is amazing! I will update the doc soon as well. we should tweet this this week. a brand new resolver.

**Comment by jorisre** [comment]
> Awesome stuff @jorisre The package size reduction is amazing! I will update the doc soon as well. we should tweet this this week. a brand new resolver.

Yeah thanks again to @mzalevski

**Pull request merged**
