### PR TITLE
Add valibot resolver

### PR DESCRIPTION
**Pull request by erikshestopal**
Adds a resolver for the new [valibot](https://github.com/fabian-hiller/valibot) library. [Codesandbox](https://codesandbox.io/s/relaxed-davinci-7gsczx?file=/src/App.tsx) link to play around with implementation.

### CODE REVIEW

**Comment by bluebill1049** [comment]
This is awesome! Thanks for producing this. I am sure a lot of users would be happy to use this lighter version of schema validation library.

**Review by bluebill1049 — APPROVED** [review]

**Comment by bluebill1049** [comment]
close #610

**Comment by fabian-hiller** [comment]
@erikshestopal thank you! 🤝

**Comment by philwolstenholme** [comment]
Thanks!

**Pull request merged**
