### PR TITLE
feat: effect-ts resolver

### PR DESCRIPTION
**Pull request by binaryartifex**
Initial submission of an effect-ts compatible react-hook-form resolver that accepts schemas from the `@effect/schema` library.

### CODE REVIEW

**Review by bluebill1049 — APPROVED** [review]
LGTM

**Review by bluebill1049 — DISMISSED** [review]

**Comment by binaryartifex** [comment]
@bluebill1049 cheers for the approvals mate. but im at a loss now as to how to fix this last failing check...

**Comment by bluebill1049** [comment]
> @bluebill1049 cheers for the approvals mate. but im at a loss now as to how to fix this last failing check...generate a whole new pnpm-lock file maybe? im cautious of doing that as its bitten me in the ass in the past, especially with older or legacy transient packages in the mix...

@jorisre do you have any idea on this issue? 🙏

**Comment by binaryartifex** [comment]
@bluebill1049 looks like that last commit bumping the pnpm versions in the github ci scripts fixed it  :thumbsup:

**Comment by bluebill1049** [comment]
nice, let's go~

**Review by bluebill1049 — APPROVED** [review]

**Comment by binaryartifex** [comment]
@bluebill1049 all good to go mate. are there scheduled releases or anything further needed from me with this pull request? when can we expect this to be merged?

**Comment by bluebill1049** [comment]
Let's release this Saturday, if something wrong I can still action it.

**Review by bluebill1049 — APPROVED** [review]

**Comment by bluebill1049** [comment]
looks like need to upgrade node to 20: 
image

**Pull request merged**
