### PR TITLE
Fix schema type error mentioned in issue 549

### PR DESCRIPTION
**Pull request by henrikvolmer**
Fixes issue https://github.com/react-hook-form/resolvers/issues/549

### CODE REVIEW

**Comment by bluebill1049** [comment]
Any chance you could add some test coverage on the fix? thank 🙏

**Comment by henrikvolmer** [comment]
Do you have any suggestions, how to test a typescript type change? In my opinion, typescript will test it automatically on compile time.

**Comment by bluebill1049** [comment]
If you can include usage in the test case would be good, that proof why the issue was there in the first place.

**Comment by henrikvolmer** [comment]
Any news here? Do you need something?

**Review by jorisre — APPROVED** [review]
LGTM! thanks for the contribution

**Comment by henrikvolmer** [comment]
@jorisre @bluebill1049 : I think this should have been better at least a minor release, since the type was `any` before and is now specialized. This is probably why some users have a problem with their types. Because of `any` the type check was disabled before and therefore wrong types didn't cause an error.

**Comment by bluebill1049** [comment]
Thanks @henrikvolmer for supporting on this issue. Yes, I think a minor version would probably be the wiser release.

**Comment by henrikvolmer** [comment]
@bluebill1049 : So how we move on? Can you change the patch version to a minor version?

**Comment by jorisre** [comment]
We can:
- Update the release note
- Re-release a minor version with a release note

@bluebill1049 What do you prefer?

**Comment by bluebill1049** [comment]
I think we just update the release note would be the better choice, cause the patch is already release. thanks @jorisre 🙏

**Comment by jorisre** [comment]
Done https://github.com/react-hook-form/resolvers/releases/tag/v3.1.1

**Pull request merged**
