### PR TITLE
Renamed private packages to avoid ambiguity with existing official packages. This should mitigate false positives during image scans.

### PR DESCRIPTION
**Pull request by Fallibilist**
This PR addresses the issue raised here: https://github.com/react-hook-form/resolvers/issues/423

This change was pretty minor but I did have a couple of questions:
- Would you prefer if I changed the path for these dependencies as well? I decided against it because it might be a breaking change but I can update the PR with that if you'd like.
- I get a warning about the new package names due to the double forward slashes (/) failing the regex. It doesn't have an impact since these are private packages but I wasn't sure if you would rather I use a different naming convention. Something like "@hookform/resolvers.ajv" perhaps.
image

### CODE REVIEW

**Comment by jorisre** [comment]
I can't test right now but I'm sure deep import like @hookform/resolvers/zod still work if we rename the package name

**Comment by bluebill1049** [comment]
> I can't test right now but I'm not sure deep import like @hookform/resolvers/zod still work if we rename the package name

I see, that's a valid concern. @Fallibilist any chance you can valid this above?

**Comment by Fallibilist** [comment]
I ran a few tests and this seems to be fine. It looks like the path in exports is all that matters (in this case ./zod).

Here is how I tested.
I created a simple testing project which imported @hookform/resolvers from a local directory. It imported zod and ran simple schema validation.
image
image
image

This is successful. 
image

Now if I rename the export "./zod" to "./zodbroken" it breaks
image
image

If I set the import to this value then it works again.
image


This was all conducted with the zod resolver's package name as "@hookform/resolvers/zod"

Here are those two files if you want to test yourself:
`{
  "name": "export-test",
  "version": "1.0.0",
  "description": "",
  "main": "testExports.js",
  "type": "module",
  "scripts": {
    "start": "node testExports.js",
    "zod": "^3.11.6"
  },
  "dependencies": {
    "@hookform/resolvers": "./resolvers"
  }
}`

`import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';

const schema = z.object({
  name: z.string().min(1, { message: 'Required' }),
  age: z.number().min(10),
});

console.log(await zodResolver(schema)({name: 'Name', age: 5}, {}, {}));
`

**Comment by jorisre** [comment]
Thanks a ton for your contribution ! Looks good to me :)

**Pull request merged**
