### PR TITLE
change target ES2017 to es5

### LINKED ISSUE #35: IE11 crashing with v0.1.0 and react-hook-form v6.08
It reports syntax error on this line:

`const parseErrorSchema = (error, validateAllFieldCriteria) => ...`

which is the code of the resolvers. I assume this needs some transpiling since IE doesn't know about const keyword?

### PR DESCRIPTION
**Pull request by kotarella1110**
close #35

### CODE REVIEW

**Comment by kotarella1110** [comment]
@bluebill1049 Since the target is changed to es5, the size after build will increase, but I think it can be used with IE11.

**Comment by bluebill1049** [comment]
Thanks very much @kotarella1110 🙏 bloody IE...

**Comment by kotarella1110** [comment]
@bluebill1049 I think this fix should be applied to @hookform packages as well. What do you think?

**Comment by bluebill1049** [comment]
I agree @kotarella1110 🙏

**Comment by bluebill1049** [comment]
until we stop supporting ie11.

**Comment by kotarella1110** [comment]
@bluebill1049 yea. I will fix 👍

**Comment by dylanhotfire** [comment]
Are you able to publish a release for this? It looks like index.cjs.developmenet.js has a compiled version of parseErrorSchema for the yup resolver, with a legitimate syntax error in IE and I'm wondering if this will fix it.

**Comment by bluebill1049** [comment]
@dylanhotfire will release a beta for you to test.

**Comment by bluebill1049** [comment]
`0.0.7-beta.1`

**Comment by dylanhotfire** [comment]
Works like a charm. Thanks!

**Comment by bluebill1049** [comment]
hey @kotarella1110 we may want to pause rolling this out. it does increase the package size quite a lot 👍 (probably except devtool package)

https://bundlephobia.com/result?p=@hookform/resolvers@0.0.7-beta.1

**Comment by bluebill1049** [comment]
do we have the option to build an IE 11 build as well?

**Comment by kotarella1110** [comment]
@bluebill1049 I think we need to build for IE11 like the core lib.

**Pull request merged**
